### ISSUE TITLE
テーブル｢飲食店_メニュー｣の列｢メニュータグ｣は別テーブルで定義したほうが良い

### ISSUE THREAD

**Issue by ghost** [codeforjapan/OPEN-EATS-JAPAN#5]
タグ情報を１カラムでセミコロン(;)で区切って入力する方法は､SQLアンチパターンのジェイウォークに該当するかと思います｡
そのためタグ情報の更新時にデータの妥当性を担保するのはユーザー､アプリケーション側に委ねられ､最悪データ崩壊を招く恐れがあります｡また､SQLでタグ情報で検索を行う処理がLike演算となり､インデックスが効かない可能性があります｡

解決策として､タグ用の新規でテーブル｢飲食店_メニュータグ｣と､交差テーブル｢飲食店_メニュー_タグ関係｣を作成するのは如何でしょうか?

※テーブル名､物理名､論理名等々は案です

**Table ｢飲食店_メニュー_タグ｣** 
|No  |物理名 |論理名 |型 |その他|
|---  |---       |---       |--- |--- |
|1| tag_id| タグID| 整数 or 文字列|  主キー|
|2| tag| タグ|文字列| 一意|

**Table ｢飲食店_メニュー_タグ関係｣  （メニューとタグを繋げる交差テーブル）**
|No  |物理名 |論理名 |型 |その他|
|---  |---       |---       |--- |--- |
|1| menu_id|メニューID| 文字列| 外部キー|
|2| tag_id| タグID| 整数 or 文字列| 主キー|

**Comment by isamu** [comment]
これはjoin/splitで処理してアプリケーション側で実装すれば良い問題に見えますね。

**Comment by ghost** [comment]
> これはjoin/splitで処理してアプリケーション側で実装すれば良い問題に見えますね。

**□公開データ取得時例**
`公開されたデータ → appで展開(splitしてDB取り込み等) →DB`

**□データをパブリック公開時例**
` DB → appでコンバート(セミコロンでjoin) → データ公開 `

な感じでしょうか?
少し私も勘違いしておりましたが､テーブル構築する訳ではなく標準フォーマットの作成なので､私の考え方が間違っていたように思っております｡

もし相違なければ本件クローズ致します｡

**Comment by isamu** [comment]
READMEにある「飲食店情報オープンデータ項目定義書」をみると、そうだと思います。

例は、そのとおりですね！

**Comment by ghost** [comment]
ご指摘ありがとうございました｡
本件クローズ致します｡
